# Generated by Django 4.2.16 on 2025-04-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_project_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='architecture',
        ),
    ]
