apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
  labels:
    app: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
      - name: e-commerce
        image: ajaff/crm:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  labels:
    app: e-commerce
spec:
  type: NodePort
  ports:
    - port: 80        # Port on the Service (accessed externally)
      targetPort: 8000 # Port your container listens on
      nodePort: 30080  # Specify a specific nodePort (use any available port above 30000)
  selector:
    app: e-commerce

